import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'String_Quartet_Staff_Group',
                'Violin_I_Music_Staff',
                'Violin_I_Music_Voice',
                'Violin_I_Rest_Voice',
                'Violin_II_Music_Staff',
                'Violin_II_Music_Voice',
                'Violin_II_Rest_Voice',
                'Viola_Music_Staff',
                'Viola_Music_Voice',
                'Viola_Rest_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [35, 49],
            ),
        ('duration', "1'36''"),
        (
            'fermata_measure_numbers',
            [36, 38, 40, 42, 48, 52, 54, 56, 58, 61],
            ),
        ('final_measure_is_fermata', True),
        ('final_measure_number', 61),
        ('first_measure_number', 35),
        ('segment_name', 'C'),
        ('segment_number', 4),
        ('start_clock_time', "1'52''"),
        ('stop_clock_time', "3'28''"),
        (
            'time_signatures',
            [
                '6/4',
                '1/4',
                '4/4',
                '1/4',
                '6/4',
                '1/4',
                '6/4',
                '1/4',
                '6/4',
                '4/4',
                '3/4',
                '4/4',
                '5/4',
                '1/4',
                '3/4',
                '3/4',
                '3/4',
                '1/4',
                '4/4',
                '1/4',
                '5/4',
                '1/4',
                '4/4',
                '1/4',
                '6/4',
                '6/4',
                '1/4',
                ],
            ),
        ]
    )
