import sys

from .library import (
    A,
    B,
    C,
    D,
    E,
    ScoreTemplate,
    accelerando_rhythm,
    cello_solo_pitches,
    cello_solo_rhythm,
    dense_getato_rhythm,
    getato_intervals,
    getato_pitches,
    glissando_rhythm,
    growth,
    harmonic_glissando_pitches,
    instruments,
    manifest,
    margin_markup,
    margin_markups,
    material_annotation_spanner,
    metronome_marks,
    perforated_counts,
    polyphony_rhythm,
    ritardando_rhythm,
    scratch_rhythm,
    sparse_getato_rhythm,
    time_signature_series,
    time_signatures,
    untied_notes,
    viola_ob_rhythm,
)

__all__ = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "ScoreTemplate",
    "getato_intervals",
    "instruments",
    "margin_markups",
    "metronome_marks",
    "time_signature_series",
    "accelerando_rhythm",
    "cello_solo_pitches",
    "cello_solo_rhythm",
    "dense_getato_rhythm",
    "getato_pitches",
    "glissando_rhythm",
    "growth",
    "harmonic_glissando_pitches",
    "manifest",
    "margin_markup",
    "material_annotation_spanner",
    "perforated_counts",
    "polyphony_rhythm",
    "ritardando_rhythm",
    "scratch_rhythm",
    "sparse_getato_rhythm",
    "time_signatures",
    "untied_notes",
    "viola_ob_rhythm",
]

if sys.version_info[:2] < (3, 9):
    raise ImportError("Requires Python 3.9 or later")
del sys
