import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'String_Quartet_Staff_Group',
                'Violin_I_Music_Staff',
                'Violin_I_Music_Voice',
                'Violin_I_Rest_Voice',
                'Violin_II_Music_Staff',
                'Violin_II_Music_Voice',
                'Violin_II_Rest_Voice',
                'Viola_Music_Staff',
                'Viola_Music_Voice',
                'Viola_Rest_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [4, 15],
            ),
        ('duration', "1'14''"),
        (
            'fermata_measure_numbers',
            [6, 8, 11, 13, 17, 19, 21, 23],
            ),
        ('final_measure_is_fermata', True),
        ('final_measure_number', 23),
        ('first_measure_number', 4),
        ('segment_name', 'A'),
        ('segment_number', 2),
        ('start_clock_time', "0'07''"),
        ('stop_clock_time', "1'21''"),
        (
            'time_signatures',
            [
                '3/4',
                '3/4',
                '1/4',
                '4/4',
                '1/4',
                '5/4',
                '4/4',
                '1/4',
                '6/4',
                '1/4',
                '6/4',
                '6/4',
                '4/4',
                '1/4',
                '6/4',
                '1/4',
                '5/4',
                '1/4',
                '3/4',
                '1/4',
                ],
            ),
        ]
    )
